# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Journal' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Journal

pod 'Firebase/Database'
pod 'Firebase/Analytics'

  target 'JournalTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JournalUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
